apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ include "springboot-ocdemo.fullname" . }}
  labels:
    {{- include "springboot-ocdemo.labels" . | nindent 4 }}
spec:
  source:
    type: Git
    git:
      uri: {{ .Values.build.git.uri | quote }}
      ref: {{ .Values.build.git.ref | quote }}
  strategy:
    type: {{ .Values.build.strategy }}
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: java:11
        namespace: openshift
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Values.build.outputImageStream | quote }}
 