{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "springboot-ocdemo.fullname" . }}
  labels:
    {{- include "springboot-ocdemo.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "springboot-ocdemo.fullname" . }}
  host: {{ .Values.route.host }}
  port:
    targetPort: {{ .Values.service.port }}
{{- end }}