apiVersion: v1
kind: Service
metadata:
  name: {{ include "springboot-ocdemo.fullname" . }}
  labels:
    {{- include "springboot-ocdemo.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "springboot-ocdemo.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}